### PR TITLE
Bug fixes for Phonex.

### PR DESCRIPTION
**Pull request by antzucaro**
@Dalvany constructing a test harness with full debugging output using the original C/C++ code let me find some additional gaps. This PR fixes those gaps. They are as follows:

- The original fall-through/switch logic for `transcode` doesn't assign the `0` code, but instead _does not mutate the returned code_ (which is a local variable in the C version and not in ours). The `transcode` function thus needed to return an `Option<char>` to handle the cases where no new code is assigned. We simply use the last calculated value instead.
- The text of the paper says leading two-character pairs are replaced by a single character, but the actual code handles this by only replacing one of the characters and lets the duplicate checking aspects of the loop handle the rest. This means instead of `WR -> R` it will do `WR -> RR`.

Some other notes based on the prior discussion:

- Zero padding is indeed present in the original implementation. For example, using my test harness: 
```
$ ./phonex 12345
BEFORE curr=1 last= code= y=1
AFTER curr=1 last= code= y=1
BEFORE curr=2 last= code= y=1
AFTER curr=2 last= code= y=1
BEFORE curr=3 last= code= y=1
AFTER curr=3 last= code= y=1
BEFORE curr=4 last= code= y=1
AFTER curr=4 last= code= y=1
BEFORE curr=5 last= code= y=1
AFTER curr=5 last= code= y=1
1000
```
- The original version will stop processing after encountering a space or a comma. Our version strips those out during the sanitization step. I think this is acceptable, as this is more of a convenience to the caller. 

All tests are passing (one test actually needed adjusting!) and clippy is happy.

### CODE REVIEW

**Comment by Dalvany** [comment]
HI @antzucaro thanks ! I'll merge the PR.
I agree it's acceptable to strip comma and space, I think usually it will anyway run on single words not on a whole text.

**Comment by Dalvany** [comment]
Do you think it's ok to make a new release now ?

**Comment by antzucaro** [comment]
@Dalvany there are some more algorithms that I'd like to explore if you wanted something bigger for a release.

**Comment by Dalvany** [comment]
Yes better to batch more in a release !
Can you provide the name of the algorithm and if you have a link to a paper, I'd like to open an issue for each one to keep track and share the work: I feel like I'm letting you do all the job

**Comment by antzucaro** [comment]
No worries, I'll create issues and we can discuss each in there.

**Pull request merged**
